### ISSUE TITLE
GenerateBundleCommand is missing in this package.

### ISSUE THREAD

**Issue by cbdiesse** [sadikoff/SensioGeneratorBundle#2]
Interested by Bundle generation for my symfony 4 based application. But this have been removed in this fork. Any reason ?

**Comment by sadikoff** [comment]
This fork is for new flex-way symfony applications that's why I removed this command. I don't see any possibility to generate bundles in flex applications.

**Comment by cbdiesse** [comment]
Does Flex-way mean no extension or bundle ? That was'nt my comprehension ... And imho SensioGeneratorBundle have nothing to do with the flex features ... Flex is actually provided to manage external dependent bundles. Application bundles are to be created in the /src directory and that don't concern flex specifications unless they want to change bundle directory structure for Symfony 4.
How do I write big applications if I have no way to break it in features bundles or are you saying bundless mean no bundle at all?
If the symfony 4 is going to restrict bundles for Applications developper with no other modularisation solution, I think it's died before born.

**Comment by sadikoff** [comment]
As for now there is no way to generate bundle in flex project but it does not mean that you can't use bundles at all or create it manualy.

**Comment by cbdiesse** [comment]
@sadikoff : thanks for your reply.
